# Generated by Django 4.2.12 on 2024-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='task',
        ),
    ]
