# Generated by Django 4.2.12 on 2024-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
